title: Painted Harmony Group - Data Science
author: Miles Porter
email: mporter@paintedharmony.com
description: Exploring data science, machine learning and other related topics.

twitter_username: miles_r_porter
github_username:  fractalbass

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics:
  tracking_code: UA-60697451-2 # Replace this with your actual tracking code
